apiVersion: v1
kind: Service
metadata:
  name: plant-disease-api-service
  labels:
    app: plant-disease-api
spec:
  type: LoadBalancer
  selector:
    app: plant-disease-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
